name: CI/CD_PUSH

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  validate-code:
    runs-on: ${{ matrix.os }}
    name: Install, Build, Check Code and Test
    strategy:
      matrix:
        os: [ubuntu-22.04]
        node_version: [20.8.1]
      fail-fast: false

    steps:
      - name: Get the last commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Check code
        run: pnpm run check:code

      - name: Test
        run: pnpm run test

      - name: Build app
        run: pnpm run build
